version: '3.8'

services:
    web:
        image: symfonycorp/cli:4.24.1
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            SYMFONY_ENV: prod
        command: [ "symfony", "server:start", "--port=8000", "--no-tls" ]

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: restau
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
